import type { UserProfile, StudySet, Source, Concept, LearningSession, Message, PracticeAttempt, PracticeDetail, PracticeEvaluation, Flashcard, ReviewPresentation, GradeResult, TopicProgress, SearchResult, ExtractionResult } from "./dto";
import type { ProfileUpdate, StudySetCreate, StudySetUpdate, SourceCreate, SourceUpdate, SessionCreate, SessionUpdate, ChatRequest, ExtractionRequest, PracticeCreate, PracticeRetry, ConceptCreate, ConceptUpdate, CardGenerate, CardUpdate, GradeRequest } from "./requests";
import type { ChatEvent } from "./sse";
export type ListQuery = { studySetId?: string; limit?: number; offset?: number };
export interface ActicallyClient {
  getProfile(): Promise<UserProfile>;
  updateProfile(input: ProfileUpdate): Promise<UserProfile>;
  listStudySets(): Promise<StudySet[]>;
  createStudySet(input: StudySetCreate): Promise<StudySet>;
  updateStudySet(id: string, input: StudySetUpdate): Promise<StudySet>;
  deleteStudySet(id: string): Promise<void>;
  listSources(studySetId: string): Promise<Source[]>;
  createSource(studySetId: string, input: SourceCreate): Promise<Source>;
  updateSource(id: string, input: SourceUpdate): Promise<Source>;
  deleteSource(id: string): Promise<void>;
  listSessions(query?: ListQuery): Promise<LearningSession[]>;
  getSession(id: string): Promise<LearningSession>;
  createSession(input: SessionCreate): Promise<LearningSession>;
  updateSession(id: string, input: SessionUpdate): Promise<LearningSession>;
  deleteSession(id: string): Promise<void>;
  listMessages(sessionId: string): Promise<Message[]>;
  streamChat(sessionId: string, input: ChatRequest, signal?: AbortSignal): AsyncIterable<ChatEvent>;
  finishSession(sessionId: string, input: ExtractionRequest): Promise<ExtractionResult>;
  listAttempts(query?: ListQuery): Promise<PracticeAttempt[]>;
  getAttempt(id: string): Promise<PracticeDetail>;
  createAttempt(input: PracticeCreate): Promise<PracticeAttempt>;
  evaluateAttempt(id: string, signal?: AbortSignal): Promise<PracticeEvaluation>;
  retryAttempt(id: string, input: PracticeRetry): Promise<PracticeAttempt>;
  listConcepts(query?: ListQuery & { status?: Concept["status"] }): Promise<Concept[]>;
  createConcept(input: ConceptCreate): Promise<Concept>;
  updateConcept(id: string, input: ConceptUpdate): Promise<Concept>;
  deleteConcept(id: string): Promise<void>;
  generateCard(input: CardGenerate): Promise<Flashcard>;
  listCards(query?: ListQuery): Promise<Flashcard[]>;
  updateCard(id: string, input: CardUpdate): Promise<Flashcard>;
  deleteCard(id: string): Promise<void>;
  getDueQueue(query?: ListQuery): Promise<ReviewPresentation[]>;
  gradeCard(cardId: string, input: GradeRequest): Promise<GradeResult>;
  getProgress(): Promise<TopicProgress[]>;
  search(query: string): Promise<SearchResult>;
}
