import { z } from "zod";
import { conceptRefSchema, conceptStatusSchema, idSchema, practiceKindSchema, revisionSchema, reviewRatingSchema, sourceRefSchema, studyModeSchema } from "./dto";
export const profileUpdateSchema = z.strictObject({ displayName: z.string().min(1).max(120).optional(), timezone: z.string().max(100).refine(v => { try { new Intl.DateTimeFormat("en", { timeZone: v }); return true; } catch { return false; } }, "Invalid IANA timezone").optional(), sidebarCollapsed: z.boolean().optional() });
export const studySetCreateSchema = z.strictObject({ subject: z.string().min(1).max(200), title: z.string().min(1).max(200), description: z.string().max(4000) });
export const studySetUpdateSchema = studySetCreateSchema.partial().extend({ expectedRevision: revisionSchema });
export const sourceCreateSchema = z.strictObject({ title: z.string().min(1).max(200), content: z.string().min(1).max(50000) });
export const sourceUpdateSchema = sourceCreateSchema.partial().extend({ expectedRevision: revisionSchema });
export const sessionCreateSchema = z.strictObject({ studySetId: idSchema.nullable(), title: z.string().min(1).max(200), mode: studyModeSchema });
export const sessionUpdateSchema = z.strictObject({ title: z.string().min(1).max(200).optional(), mode: studyModeSchema.optional(), studySetId: idSchema.nullable().optional() });
export const chatRequestSchema = z.strictObject({ content: z.string().min(1).max(16000), mode: studyModeSchema, requestId: idSchema, followUpStep: z.number().int().min(1).max(12).nullable() });
export const extractionRequestSchema = z.strictObject({ idempotencyKey: idSchema });
export const practiceCreateSchema = z.strictObject({ kind: practiceKindSchema, studySetId: idSchema, learnerText: z.string().min(1).max(16000), referenceSnapshots: z.array(conceptRefSchema).min(1).max(30), idempotencyKey: idSchema });
export const practiceRetrySchema = z.strictObject({ learnerText: z.string().min(1).max(16000), idempotencyKey: idSchema });
export const conceptCreateSchema = z.strictObject({ studySetId: idSchema, title: z.string().min(1).max(200), body: z.string().min(1).max(8000), sourceRefs: z.array(sourceRefSchema).max(20) });
export const conceptUpdateSchema = z.strictObject({ title: z.string().min(1).max(200).optional(), body: z.string().min(1).max(8000).optional(), status: conceptStatusSchema.optional(), sourceRefs: z.array(sourceRefSchema).max(20).optional(), expectedRevision: revisionSchema });
export const cardGenerateSchema = z.strictObject({ conceptId: idSchema, expectedConceptRevision: revisionSchema, idempotencyKey: idSchema });
export const cardUpdateSchema = z.strictObject({ front: z.string().min(1).max(4000), back: z.string().min(1).max(8000), expectedRevision: revisionSchema });
export const gradeRequestSchema = z.strictObject({ presentationId: idSchema, idempotencyKey: idSchema, expectedRevision: revisionSchema, rating: reviewRatingSchema });
export type ProfileUpdate = z.infer<typeof profileUpdateSchema>;
export type StudySetCreate = z.infer<typeof studySetCreateSchema>;
export type StudySetUpdate = z.infer<typeof studySetUpdateSchema>;
export type SourceCreate = z.infer<typeof sourceCreateSchema>;
export type SourceUpdate = z.infer<typeof sourceUpdateSchema>;
export type SessionCreate = z.infer<typeof sessionCreateSchema>;
export type SessionUpdate = z.infer<typeof sessionUpdateSchema>;
export type ChatRequest = z.infer<typeof chatRequestSchema>;
export type ExtractionRequest = z.infer<typeof extractionRequestSchema>;
export type PracticeCreate = z.infer<typeof practiceCreateSchema>;
export type PracticeRetry = z.infer<typeof practiceRetrySchema>;
export type ConceptCreate = z.infer<typeof conceptCreateSchema>;
export type ConceptUpdate = z.infer<typeof conceptUpdateSchema>;
export type CardGenerate = z.infer<typeof cardGenerateSchema>;
export type CardUpdate = z.infer<typeof cardUpdateSchema>;
export type GradeRequest = z.infer<typeof gradeRequestSchema>;
